apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: order-service-rollout
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/SpaceNik777/ECommerceMicroservices.git'
    targetRevision: HEAD
    path: argo/rollouts
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: ecommerce
  syncPolicy:
    automated:
      prune: true
      selfHeal: true 