version: '3.8'

services:
  order-service:
    build:
      context: .
      dockerfile: OrderService.API/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=orderservice;Username=postgres;Password=postgres
      - Kafka__BootstrapServers=kafka:9092
      - Services__UserService=http://user-service:8081
      - Services__InventoryService=http://inventory-service:8082
    depends_on:
      - postgres
      - kafka
      - user-service
      - inventory-service

  user-service:
    build:
      context: .
      dockerfile: UserService/Dockerfile
    ports:
      - "8081:8081"
    environment:
      - PORT=8081
    depends_on:
      - kafka

  inventory-service:
    build:
      context: .
      dockerfile: InventoryService/Dockerfile
    ports:
      - "8082:8082"
    environment:
      - PORT=8082
      - KAFKA_BROKERS=kafka:9092
    depends_on:
      - kafka

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_DB=orderservice
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    ports:
      - "2181:2181"
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000
    volumes:
      - zookeeper_data:/var/lib/zookeeper/data
      - zookeeper_log:/var/lib/zookeeper/log

  kafka:
    image: confluentinc/cp-kafka:7.3.0
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_DELETE_TOPIC_ENABLE=true
    volumes:
      - kafka_data:/var/lib/kafka/data
    depends_on:
      - zookeeper

volumes:
  postgres_data:
  zookeeper_data:
  zookeeper_log:
  kafka_data: 