apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgres.fullname" . }}
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
type: Opaque
data:
  username: {{ "postgres" | b64enc }}
  password: {{ "postgres" | b64enc }} 