apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: ingress-error-rate
  namespace: ecommerce
spec:
  metrics:
    - name: error-rate
      interval: 1m
      count: 5
      failureLimit: 1
      provider:
        prometheus:
          address: http://prometheus:9090
          query: |
            sum(rate(nginx_ingress_controller_requests{status=~"5.."}[1m]))
            /
            sum(rate(nginx_ingress_controller_requests[1m])) 