apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "vault.fullname" . }}-agent-config
  labels:
    {{- include "vault.labels" . | nindent 4 }}
data:
  vault-agent-config.hcl: |
    exit_after_auth = true
    pid_file = "/home/vault/pidfile"
    
    auto_auth {
      method "kubernetes" {
        mount_path = "auth/kubernetes"
        config = {
          role = "postgres"
        }
      }
    }
    
    template {
      destination = "/vault/secrets/postgres"
      contents = <<EOH
      {{- `{{- with secret "secret/data/postgres" }}
      POSTGRES_USER={{ .Data.data.username }}
      POSTGRES_PASSWORD={{ .Data.data.password }}
      {{- end }}` }}
      EOH
    } 