apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: ingress-error-rate
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "order-service.labels" . | nindent 4 }}
spec:
  metrics:
    - name: error-rate
      interval: 30s
      count: 3
      failureLimit: 1
      provider:
        prometheus:
          address: http://prometheus:9090
          query: |
            sum(rate(nginx_ingress_controller_requests{status=~"5.."}[30s]))
            /
            sum(rate(nginx_ingress_controller_requests[30s])) 