apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "order-service.fullname" . }}-config
  labels:
    {{- include "order-service.labels" . | nindent 4 }}
data:
  ASPNETCORE_ENVIRONMENT: "Development"
  ASPNETCORE_URLS: "http://+:8080"
  Kafka__BootstrapServers: "kafka:9092"
  Services__UserService: "http://user-service:8081"
  Services__InventoryService: "http://inventory-service:8082"
  POSTGRES_DB: "orderservice"
  POSTGRES_HOST: "postgres"
  POSTGRES_PORT: "5432" 